theme: jekyll-theme-cayman
title: Windows Server 2019 Infrastructure Project
description: Designing and optimizing network infrastructures using Windows Server 2019, featuring Active Directory, DHCP, DNS, and PowerShell automation.
